### ISSUE TITLE
00datafiltering error: 

### ISSUE THREAD

**Issue by hirenbioinfo** [mskwark/genomeDCA#2]
I was having a try with 300 ecoli genome to run genomeDAC but unfortunatly got some error in step1. Could you please help me out to  fix the error
$python 00process.py /home/biotools/genomeDAC/genomeDCA-master/core_gene_alignment.aln core_out

Error:
Traceback (most recent call last):
  File "00process.py", line 111, in <module>
    o = parsefile(infile)
  File "00process.py", line 63, in parsefile
    if float(q[2]) > 0:
IndexError: list index out of range

**Comment by mskwark** [comment]
Dear HIren,
The current version in GitHub should have this issue fixed. This error tended to occur in case of monoallellic positions, which would nevertheless be discarded before further computation.
Cheers,
Marcin
